In [2]:
# imports
import pandas as pd
from pycaret.classification import *

In [3]:
# load and choose categoricals
df = pd.read_excel('./data/heart.xlsx', engine='openpyxl')
cats_ = ['sex_M_F', 'chest_pain_value', 'ECG_value', 'ST_slope_peak', 'defect_diag']
df.head(5)

,age_yr,sex_M_F,chest_pain_value,resting_BP_mm_Hg,cholesterol_mg_dl,fasting_blood_sugar_high,ECG_value,max_HR,exercise_angina,ST_depresssion_exercise,ST_slope_peak,number_vessels_involved,defect_diag,heart_disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,1
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,0
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,1
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,0
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,0

In [4]:
#setup target
ex = setup(df, target='heart_disease', categorical_features=cats_)

In [5]:
# find "best model"
best_model = compare_models()